# Site settings
title: Your Blog Title
description: "A simple and elegant blog"
baseurl: "/cloud-lab-ia2/" # the subpath of your site, e.g. /blog
url: "https://cipher-god.github.io/" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown

# Exclude these files and directories from the final build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .git
  - .gitignore

# Permalink structure for pages
defaults:
  - scope:
      path: "" # empty string means all files in the project
      type: "pages"
    values:
      layout: "default" # default layout for pages

# Collection settings
collections:
  pages:
    output: true # enable output for pages collection