# Site settings
title: Cloud IA 2
email: 
description: > # this means to ignore newlines until "baseurl:"
  Blog Template
baseurl: "/cloud-lab-ia2"
url: "https://cipher-god.github.io/cloud-lab-ia2/"
theme: jekyll-theme-minimal

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links